-- Create Barang table
create table barang (
  id bigint primary key generated by default as identity,
  nama_barang text not null,
  category text not null, -- 'makanan' or 'minuman'
  harga numeric not null,
  stok integer default 0,
  is_available integer default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Insert Dummy Data for Barang
INSERT INTO barang (nama_barang, category, harga, stok) VALUES
('Air Mineral 600ml', 'minuman', 5000, 100),
('Isotonic Drink', 'minuman', 8000, 50),
('Teh Botol', 'minuman', 7000, 50),
('Kopi Hitam', 'minuman', 10000, 30),
('Mie Goreng Instan', 'makanan', 12000, 40),
('Roti Bakar', 'makanan', 15000, 20),
('Nasi Goreng', 'makanan', 25000, 15),
('Kentang Goreng', 'makanan', 18000, 25);
