-- Create Pemasukan Detail table
create table pemasukan_detail (
  id bigint primary key generated by default as identity,
  pemasukan_id bigint not null references pemasukan(id) on delete cascade,
  nomor_invoice text not null references pemasukan(nomor_invoice) on delete cascade,
  barang_id bigint references barang(id),
  nama_barang text not null,
  harga_satuan numeric not null,
  qty integer not null,
  subtotal numeric not null,
  created_at timestamptz default now()
);
