create table field_images (
  id bigint primary key generated by default as identity,
  field_id bigint references fields(id) on delete cascade,
  url_image text not null,
  created_at timestamptz default now()
);
