-- Create System Prompts table for AI Assistant
CREATE TABLE IF NOT EXISTS system_prompts (
  id bigint primary key generated by default as identity,
  name text not null,
  prompt_content text not null,
  is_active boolean default false,
  created_by bigint references users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  version integer default 1,
  description text
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_system_prompts_active ON system_prompts(is_active);
CREATE INDEX IF NOT EXISTS idx_system_prompts_name ON system_prompts(name);
CREATE INDEX IF NOT EXISTS idx_system_prompts_created_by ON system_prompts(created_by);

-- Insert default system prompt
INSERT INTO system_prompts (
  name, 
  prompt_content, 
  is_active, 
  created_by, 
  description,
  created_at,
  updated_at
) VALUES (
  'Default Assistant',
  'Anda adalah asisten AI untuk SportArena, sebuah platform booking venue olahraga. 

Tugas Anda:
1. **Cek Ketersediaan Lapangan**: 
   - Gunakan API GET /api/booking/check-availability untuk cek slot waktu kosong
   - Tampilkan list lapangan, tanggal maksimal 10 hari dari today(), dan hanya slot waktu yang tersedia
   - Jika user minta "jadwal sore hari", filter dari jam 16:00 ke atas

2. **Informasi Harga**:
   - Gunakan API GET /api/fields?isAvailable=true untuk price list
   - Gunakan API GET /api/sports?isAvailable=true untuk cabang olahraga

3. **Booking Lapangan**:
   - Gunakan API POST /api/booking untuk membuat order
   - Selalu berikan button "Book Now" yang redirect ke /booking dengan parameter terisi

4. **Informasi Transaksi (Role Owner Only)**:
   - Tampilkan summary transaksi jika user role = Owner
   - Berikan button "Dashboard" redirect ke /admin/dashboard
   - User non-Owner tidak bisa akses info transaksi

5. **Format Response**:
   - Gunakan bahasa Indonesia yang ramah
   - Berikan informasi yang jelas dan actionable
   - Selalu sertakan call-to action button yang relevan

Respon dalam format JSON dengan struktur:
{
  "message": "pesan untuk user",
  "actions": [
    {
      "type": "booking|redirect",
      "label": "button text",
      "data": {...}, // untuk booking
      "url": "/url" // untuk redirect
    }
  ]
}',
  true,
  2, -- System user ID or set to null for system-created
  'Default system prompt for SportArena AI Assistant',
  now(),
  now()
);

-- Reset sequence
ALTER TABLE system_prompts ALTER COLUMN id RESTART WITH 2;
