-- Insert Cashier Role
INSERT INTO roles (role_name, description) VALUES ('cashier', 'Can access Cashier menu and Booking');

-- Create Pemasukan table
create table pemasukan (
  id bigint primary key generated by default as identity,
  nomor_invoice text unique not null,
  id_booking bigint references bookings(id),
  tanggal_pembayaran timestamptz default now(),
  amount numeric not null,
  created_at timestamptz default now(),
  created_by text,
  updated_at timestamptz default now(),
  updated_by text
);
