-- Add gambar_barang column if it doesn't exist (safe way usually involves checking, but for this dev setup we can just alter or recreate)
-- We will recreate the table to be clean and match exact requirements
DROP TABLE IF EXISTS barang CASCADE;

create table barang (
  id bigint primary key generated by default as identity,
  nama_barang text not null,
  category text not null, -- 'makanan' or 'minuman'
  harga numeric not null,
  stok integer default 100,
  gambar_barang text,
  is_available integer default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Insert Data: 5 Makanan
INSERT INTO barang (nama_barang, category, harga, stok, gambar_barang) VALUES
('Nasi Goreng Spesial', 'makanan', 25000, 50, 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=300&h=300'),
('Mie Goreng Jawa', 'makanan', 22000, 45, 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&q=80&w=300&h=300'),
('Ayam Geprek', 'makanan', 20000, 40, 'https://images.unsplash.com/photo-1642163767596-a289f3c2a9d9?auto=format&fit=crop&q=80&w=300&h=300'),
('Roti Bakar Coklat Keju', 'makanan', 15000, 30, 'https://images.unsplash.com/photo-1541557435984-1c79685a082b?auto=format&fit=crop&q=80&w=300&h=300'),
('Kentang Goreng', 'makanan', 12000, 60, 'https://images.unsplash.com/photo-1518013431117-e5952c87455d?auto=format&fit=crop&q=80&w=300&h=300');

-- Insert Data: 5 Minuman
INSERT INTO barang (nama_barang, category, harga, stok, gambar_barang) VALUES
('Es Teh Manis', 'minuman', 5000, 100, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=300&h=300'),
('Jus Jeruk', 'minuman', 12000, 50, 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&q=80&w=300&h=300'),
('Kopi Susu Gula Aren', 'minuman', 18000, 40, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=300&h=300'),
('Air Mineral', 'minuman', 4000, 200, 'https://images.unsplash.com/photo-1564414250694-430066f45222?auto=format&fit=crop&q=80&w=300&h=300'),
('Soda Gembira', 'minuman', 15000, 35, 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=300&h=300');
